name: Terraform Deploy

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Remove old lock file
      run: rm -f .terraform.lock.hcl

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Generate SSH key
      run: |
        ssh-keygen -t rsa -b 2048 -f key.pem -N ""
    - name: Setup SSH key
      run: |
       echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
       chmod 600 key.pem

    - name: Terraform Init
      run: terraform init -reconfigure

    - name: Terraform Plan
      run: terraform plan -lock=false -var-file="terraform.tfvars" -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Get EC2 Public IPs
      run: |
         echo "Getting EC2 IPs..."

         for ip in $(terraform output -json ec2_public_ips | jq -r '.[]'); do
         echo "Checking instance: $ip"

         ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$ip "nginx -v 2>&1"
         ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$ip "docker --version"

         echo "----------------------"
         done

    - name: Upload file to S3
      run: |
        echo "Hello from pipeline" > test.txt
        aws s3 cp test.txt s3://$(terraform output -raw s3_bucket_name)

    - name: List S3 files
      run: aws s3 ls s3://$(terraform output -raw s3_bucket_name)
